### PR TITLE
add time consume parameter to debug functionality

### PR DESCRIPTION
**Pull request by zinuzoid**
to be able to fully integrate with debugbar it need query time consumed value.

### CODE REVIEW

**Comment by layanto** [comment]
Hi,
I am looking for this functionality too. Had a look at your pull request, isn't this only timing the PDO prepare (preparing the SQL query) but not timing the PDO fetch (actually getting data from database)?

**Comment by zinuzoid** [comment]
@layanto Seem like you are correct that it's not include fetch time but only prepare and execute time.

This is an example about timing data I got.
screenshot from 2014-09-11 00 25 57

**Comment by layanto** [comment]
@zinuzoid I will have another look at this to confirm if indeed fetch is not timed. My current approach to this is similar to yours but as I am attempting to integrate NotORM into Symfony and its Profile/Web Debug Toolbar in dev environment, I couldn't use microtime as you had. I created two new callback functions - debugPre and debugPost in addition to the existing debug. debugPre is called at the beginning of function query and debugPost is called just before function query returns. In debugPre callback function I start Symfomy's stopwatch and I stop the stopwatch in debugPost. This way I get duration and timeline of query relative to other action of Symfony (controller, rendering view, etc). But this only time inside function query as your pull request.

**Comment by vrana** [comment]
I've added debugTimer callback which is called after executing the query.

**Comment by layanto** [comment]
@vrana,
Is is possible to have debugTimer after fetching data? I know this will include network latency but the timing information can be used to compare and optimize queries. Just timing the query may result in similar times regardless of how efficient or inefficient the query is in fetching data?

**Comment by vrana** [comment]
I don't plan to add that support.

**Pull request closed without merging**
